version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_app
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
